const products = [
  {
    id: 0,
    name: "Hantla 20kg",
    description: `Hantle stanowią jeden z ważniejszych elementów każdego treningu. Lekkie obciążenia 20 kg stosowane są zarówno przez osoby ćwiczące typowo siłowo, 
    jak i przez biegaczy czy kolarzy, którzy urozmaicają swoje plany treningowe o trening funkcjonalny.`,
    category: "hantle",
    price: 260,
    image: "./images/hantla20kg.jpg",
    sale: true,
    saleAmount: 200,
  },
  {
    id: 1,
    name: "Hantla stalowa gumowana 40 kg",
    description: `Hantla zapewnia pewny chwyt, który umożliwia stabilne utrzymanie sprzętu bez możliwości przypadkowego przemieszczenia. 
    Wysoka jakość materiałów utrzymanych w kolorystyce czarno-czerwonej`,
    category: "hantle",
    price: 650,
    image: "./images/hantla40kg.png",
  },
  {
    id: 2,
    name: "Zestaw regulowanych sztangielek",
    description: `Innowacyjny produkt, który pozwala na wykonywanie różnorodnych ćwiczeń w domowym zaciszu. Z jednego zestawu stworzysz sztangę oraz hantel.`,
    category: "hantle",
    price: 1350,
    image: "./images/hantle_reg.jpg",
    sale: true,
    saleAmount: 150,
  },
  {
    id: 3,
    name: "Stojak z ogumieniem na hantle",
    description: `Profesjonalny sprzęt, który znajdzie zastosowanie w każdej siłowni. Stojak zajmuje niewiele miejsca i sprawdzi się także w mniejszych salach treningowych.`,
    category: "stojaki",
    price: 4500,
    image: "./images/stojak1.jpg",
  },
  {
    id: 4,
    name: "Stojak na sztangi",
    description: `To profesjonalne rozwiązanie do przechowywania sztang i gryfów. Dzięki niemu łatwiej będzie Ci utrzymać ład i porządek.`,
    category: "stojaki",
    price: 3000,
    image: "./images/stojak2.jpg",
  },
  {
    id: 5,
    name: "Zestaw talerzy olimpijskich",
    description: `Zestaw 8 talerzy, o łącznej wadze 140 kg.`,
    category: "zestawy obciążeń",
    price: 4500,
    image: "./images/zestaw1.jpg",
    sale: true,
    saleAmount: 250,
  },
  {
    id: 6,
    name: "Zestaw obciążeń żeliwnych",
    description: `Zawartość zestawu: 4x Obciążenie 1,25kg, 6x Obciążenie 2,5kg, 2x Obciążenie 5kg.`,
    category: "zestawy obciążeń",
    price: 400,
    image: "./images/zestaw2.jpg",
  },
  {
    id: 7,
    name: "Hantla kettlebell 10 kg",
    description: `Kettlebell żeliwny 10 kg - obowiązkowy element domowej siłowni.`,
    category: "hantle kettlebell",
    price: 120,
    image: "./images/ketl1.jpg",
  },
  {
    id: 8,
    name: "Hantla kettlebell 4 kg",
    description: `Kettlebell żeliwny 4 kg - obowiązkowy element domowej siłowni.`,
    category: "hantle kettlebell",
    price: 60,
    image: "./images/ketl2.jpg",
    sale: true,
    saleAmount: 20,
  },
  {
    id: 9,
    name: "Hantla kettlebell 28 kg",
    description: `Kettlebell żeliwny 28 kg - obowiązkowy element domowej siłowni.`,
    category: "hantle kettlebell",
    price: 330,
    image: "./images/ketl3.jpg",
  },
];
